name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    container:
      image: swift:5.3-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread